import { BASE_URL, ENDPOINTS, SERVER_ERROR, TOKEN_EXPIRED_ERROR } from './api';
import {
  MAX_NAME_LENGTH,
  MESSAGE_REQUIRED,
  MIN_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
} from './authorization';
import {
  FROM_MAIN,
  FROM_TEXTBOOK,
  GAME_ROUND_TIME,
  LOCAL_STORAGE_KEYS,
  ROUTER_PATHS,
} from './common';
import { GAME_TYPES, STARTED_WORD_INDEX } from './games';
import {
  DELTA,
  EASY_WORD,
  HARD_WORD,
  MAX_GROUP,
  MAX_GROUP_FOR_GUESTS,
  MAX_GROUP_FOR_USERS,
  MAX_PAGE,
  MIN_GROUP,
  MIN_PAGE,
  NOT_EASY_WORD,
  WORDS_PER_PAGE,
} from './words';

export {
  ROUTER_PATHS,
  BASE_URL,
  ENDPOINTS,
  LOCAL_STORAGE_KEYS,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  MESSAGE_REQUIRED,
  SERVER_ERROR,
  MIN_GROUP,
  MIN_PAGE,
  MAX_GROUP,
  MAX_PAGE,
  DELTA,
  HARD_WORD,
  EASY_WORD,
  TOKEN_EXPIRED_ERROR,
  MAX_GROUP_FOR_USERS,
  MAX_GROUP_FOR_GUESTS,
  WORDS_PER_PAGE,
  FROM_MAIN,
  FROM_TEXTBOOK,
  NOT_EASY_WORD,
  GAME_ROUND_TIME,
  STARTED_WORD_INDEX,
  GAME_TYPES,
};
