import { ROUTER_PATHS, LOCAL_STORAGE_KEYS } from './common';
import { BASE_URL, ENDPOINTS } from './api';
import {
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  MESSAGE_REQUIRED,
  SERVER_ERROR,
} from './authorization';
import { MIN_GROUP, MIN_PAGE, MAX_GROUP, MAX_PAGE } from './words';

export {
  ROUTER_PATHS,
  BASE_URL,
  ENDPOINTS,
  LOCAL_STORAGE_KEYS,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  MESSAGE_REQUIRED,
  SERVER_ERROR,
  MIN_GROUP,
  MIN_PAGE,
  MAX_GROUP,
  MAX_PAGE,
};
