import { ROUTER_PATHS, LOCAL_STORAGE_KEYS } from './common';
import { BASE_URL, ENDPOINTS, SERVER_ERROR, TOKEN_EXPIRED_ERROR } from './api';
import {
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  MESSAGE_REQUIRED,
} from './authorization';
import {
  MIN_GROUP,
  MIN_PAGE,
  MAX_GROUP,
  MAX_PAGE,
  DELTA,
  HARD_WORD,
  EASY_WORD,
  MAX_GROUP_FOR_USERS,
  MAX_GROUP_FOR_GUESTS,
} from './words';

export {
  ROUTER_PATHS,
  BASE_URL,
  ENDPOINTS,
  LOCAL_STORAGE_KEYS,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  MESSAGE_REQUIRED,
  SERVER_ERROR,
  MIN_GROUP,
  MIN_PAGE,
  MAX_GROUP,
  MAX_PAGE,
  DELTA,
  HARD_WORD,
  EASY_WORD,
  TOKEN_EXPIRED_ERROR,
  MAX_GROUP_FOR_USERS,
  MAX_GROUP_FOR_GUESTS,
};
